spring:
  application:
    name: batch-service
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource: 
    url: jdbc:mysql://localhost:3306/cartdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update	

batch:
  file:
    input-directory: C:\Santosh Workspace\Batch\Input
    archive-directory: C:\Santosh Workspace\Batch\Archive
    error-directory: C:\Santosh Workspace\Batch\Error
